name: miva_pos_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  powersync: ^1.5.2
  path_provider: ^2.1.3
  supabase_flutter: ^2.5.7
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  lazy_load_indexed_stack: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7
  google_fonts: ^6.2.1
  easy_sidemenu: ^0.6.0
  flutter_staggered_grid_view: ^0.7.0
  loading_animation_widget: ^1.2.1
  dropdown_button2: ^2.3.9
  flutter_form_builder: ^9.3.0
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  form_builder_validators: ^11.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  awesome_dialog: ^3.2.1
  internet_connection_checker_plus: ^2.5.0
  cached_network_image: ^3.3.1
  insta_image_viewer: ^1.0.4
  simple_barcode_scanner: ^0.1.1
  flutter_barcode_listener: ^0.1.4
  input_quantity: ^2.3.4
  just_audio: ^0.9.39
  device_preview: ^1.2.0
  animations: ^2.0.11
  action_slider: ^0.7.0
  choice: ^2.3.2
  animated_toggle_switch: ^0.8.2
  toggle_switch: ^2.3.0
  animated_emoji: ^3.1.0
  shared_preferences: ^2.3.0
  http: ^1.2.2
  image: ^4.2.0
  esc_pos_utils_plus:
    path: vendor/esc_pos_utils_plus
  print_bluetooth_thermal:
    path: vendor/print_bluetooth_thermal

dependency_overrides:
  esc_pos_utils_plus:
    path: vendor/esc_pos_utils_plus
  print_bluetooth_thermal:
    path: vendor/print_bluetooth_thermal

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/sounds/
    - packages/animated_emoji/lottie/heartFace.json
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
