name: miva_pos_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  powersync: ^1.5.2
  path_provider: ^2.1.3
  supabase_flutter: ^2.5.7
  flutter_dotenv: ^5.1.0
  logging: ^1.2.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  lazy_load_indexed_stack: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7
  google_fonts: ^6.2.1
  easy_sidemenu: ^0.6.0
  flutter_staggered_grid_view: ^0.7.0
  loading_animation_widget: ^1.2.1
  dropdown_button2: ^2.3.9
  flutter_form_builder: ^9.3.0
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  form_builder_validators: ^11.0.0
  currency_text_input_formatter: ^2.2.3

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
